version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
  ignore:
  - dependency-name: guzzlehttp/psr7
    versions:
    - 1.7.0
    - 1.8.1
  - dependency-name: php-http/message
    versions:
    - 1.10.0
  rebase-strategy: disabled
